const TOURNAMENT_PLAYERS = [
    "incidentSSS",
    "Alihan™",
    "Нурофен?",
    "Арно",
    "EXCESS",
    "Амин)",
    "Petux",
    "man888sur",
    "D.K",
    "broplay",
    "IDI",
    "FotonX17",
    "Нрнр",
    "_KING_2.0",
    "Lord",
    "Ramzes faraon",
    "Azok",
    "_Magatemir11_"
];