const TOURNAMENT_PLAYERS = [
    "Арно",
    "EXCESS",
    "Амин)",
    "Ramzes faraon",
    "D.K",
    "Lord",
    "Petux",
    "man888sur",
    "_KING_2.0",
    "the first",
    "broplay",
    "Alihan™",
    "Azok",
    "FotonX17",
    "IDI",
    "_Magatemir11_",
    "Нурофен?",
    "Нрнр",
    "incidentSSS"
];